### ISSUE TITLE
Table header missing

### ISSUE THREAD

**Issue by rixx** [thombashi/pytest-md-report#9]
I tried running pytest-md-report in a GitHub workflow, and the resulting table didn't have a header, which breaks table rendering. [Example workflow](https://github.com/pretalx/pretalx/actions/runs/9127666050)

**Comment by thombashi** [comment]
@rixx 
As far as I have tried, the output report of `pytest-md-report` to a job summary in a GitHub workflow looks fine.
![md-report_job-summary](https://github.com/thombashi/pytest-md-report/assets/15517661/7e44e7ab-ac83-451a-955b-25cb75fb7e75)

I think `tail -n+2` is the cause of the missing of the table header:
https://github.com/pretalx/pretalx/blob/5acd81fe545670d81b87aa7ea0760b6368bb4223/.github/workflows/tests.yml#L107
What happens if you simply `cat` the report file?
